version: "3.7"
services:
  prime_api:
    container_name: prime_api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - 5000:80
      - 5008:443
      - 5009:5000
    depends_on:
      - "prime_db"
      - "prime_science"
      
  prime_db:
    container_name: prime_db
    build:
      context: .
      dockerfile: PrimeCalculator.DB/Dockerfile
    networks:
      - my_network
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  prime_science:
    networks:
      - my_network
    container_name: prime_science
    build:
      context: ./Science
      dockerfile: Dockerfile

networks:
  my_network:
    driver: bridge
    
volumes:
  postgres:
  archive:
  temp:
  data:
  node_modules: