version: '3.4'

services:
  pet.db:
    image: balazs/myrepo:prime_db
    build:
      context: .
      dockerfile: PrimeCalculator.DB/Dockerfile
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
volumes:
  postgres:
  archive:
  temp:
  data:
  node_modules: